#!/usr/bin/env bash

nick="$1"
mesg="$2"
ircd="$3"
netw="$4"
chan="$5"
self="$6"

read -r cmd extra <<< "$mesg"
if [[ "$mesg" =~ .*\>.+ ]]; then
    read -r nicks <<< "${extra#*>}"
    read -r extra <<< "${extra%>*}"
fi

if [[ "$nicks" == "@all" ]]; then
    printf -- "/names %s\n" "$chan"
    nicks=""
    while test -z "$nicks"; do # wait for the response
        nicks="$(tail -n2 "$ircd/$netw/out" | grep "[[:digit:]-]\+ [[:digit:]:]\+ = $chan" | cut -d" " -f5-)"
        sleep .5
    done
fi

commands=(
    list
    calc
    echo
    fortune
    ping
    slap
    url
    whereami
    ampoor
)
case "$cmd" in
	ampoor)
        num=40
        repetition=0
        tail -$num $ircd/$netw/$chan/out >/tmp/ampoor.out
        while [[ "$repetition" -lt "$num" ]]
        do 
            ((repetition+=1))

            link=$(cat /tmp/ampoor.out | tail -$repetition | head -1 | \
                sed -n 's;.*\(http[^ ]*\).*;\1;p')
            if [[ -z $link ]]; then continue; fi
            if curl -I $link 2>/dev/null | grep -i "Content-type" | grep -i -e "jpeg\|png\|jpg" -q
            then
                    wget $link -O /tmp/botimg 2>/dev/null
                    hash=$(md5sum /tmp/botimg)
                    hash=${hash:0:8}
                    mv /tmp/botimg /tmp/$hash
                    ext=$(file -b /tmp/$hash | awk '{print $1}')
                    mv /tmp/$hash /tmp/$hash.$ext
                    filename=$hash.$ext
                    convert /tmp/$filename -resize 200x200 /var/www/uploads/img/res_$filename
                    echo "http://carta.im/uploads/img/res_$filename"
                    break
            fi

        done

	;;
esac

